export const boardData = [
    { id: 0, name: "recursion", active: false, clicked: false},
    { id: 1, name: "currying", active: false, clicked: false},
    { id: 2, name: "let", active: false, clicked: false },
    { id: 3, name: "SetState",    active: false, clicked: false },
    { id: 4, name: "closures", active: false, clicked: false},
    { id: 5, name: "var",active: false, clicked: false },
    { id: 6, name: "async", active: false, clicked: false },
    { id: 7, name: "promises", active: false, clicked: false },
    { id: 8, name: "HOCs",    active: false, clicked: false},
    { id: 9, name: "useMemo", active: false, clicked: false},
    { id: 10, name: "arrow functions",active: false, clicked: false},
    { id: 11, name: "const", active: false, clicked: false},
    { id: 12, name: "I'M TAKEN", active: true, clicked: true},
    { id: 13, name: "classes",    active: false, clicked: false},
    { id: 14, name: "context-ApI", active: false, clicked: false},
    { id: 15, name: "Jest",active: false, clicked: false},
    { id: 16, name: "Code-splitting", active: false, clicked: false},
    { id: 17, name: "cookies", active: false, clicked: false},
    { id: 18, name: "props",    active: false, clicked: false},
    { id: 19, name: "router", active: false, clicked: false},
    { id: 20, name: "Redux",active: false, clicked: false},
    { id: 21, name: "scope", active: false, clicked: false},
    { id: 22, name: "IFFEs", active: false, clicked: false},
    { id: 23, name: "useEffect",    active: false, clicked: false},
    { id: 24, name: "Fetch /Axios", active: false, clicked: false},
    ]

    export const winningCombinations = [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [0, 5, 10, 15, 20],
        [1, 6, 11, 16, 21],
        [2, 7, 12, 17, 22],
        [3, 8, 13, 18, 23],
        [4, 9, 14, 19, 24],
        [0, 6, 12, 18, 24],
        [4, 8, 12, 16, 20],
      ];

